name: Update Asteroid Impact Tracker

on:
  # Run on schedule (daily at midnight UTC)
  schedule:
    - cron: '0 0 * * *'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-tracker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
      
      - name: Get current date
        id: date
        run: echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      
      - name: Fetch latest impact probability
        id: fetch-probability
        run: |
          probability=$(curl -s "https://ssd-api.jpl.nasa.gov/sentry.api?des=2024%20YR4" | jq '.summary.ip | tonumber * 100000 | round / 1000')
          echo "probability=$probability" >> $GITHUB_OUTPUT
          echo "Fetched probability: $probability%"
      
      - name: Update HTML file
        run: |
          # Create new table row
          NEW_ROW="                <tr>
                    <td>${{ steps.date.outputs.today }}</td>
                    <td>${{ steps.fetch-probability.outputs.probability }}</td>
                    <td></td>
                </tr>
                <!-- rowslug -->"
          
          # Replace the line containing the rowslug comment with our new row
          sed -i'.sedbak' "/<!-- rowslug -->/c\\${NEW_ROW}" index.html
      
      - name: Check for changes
        id: check-changes
        run: |
          if git diff --quiet index.html; then
            echo "No changes detected"
            echo "changes_made=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "changes_made=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit changes if any
        if: steps.check-changes.outputs.changes_made == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.html
          git commit -m "Update asteroid impact probability data for ${{ steps.date.outputs.today }}"
      
      - name: Push changes
        if: steps.check-changes.outputs.changes_made == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
